[package]
name = "leo-state"
version = "1.0.6"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "State parser of the Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.leo-input]
path = "../input"
version = "1.0.6"

[dependencies.leo-ast]
path = "../ast"
version = "1.0.6"

[dependencies.snarkos-algorithms]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"
default-features = false

[dependencies.snarkos-curves]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"
default-features = false

[dependencies.snarkos-dpc]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"
default-features = false

[dependencies.snarkos-errors]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"
default-features = false

[dependencies.snarkos-models]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"
default-features = false

[dependencies.snarkos-objects]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"
default-features = false

[dependencies.snarkos-utilities]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"

[dependencies.indexmap]
version = "1.6.0"
features = ["serde-1"]

[dependencies.rand]
version = "0.7"

[dependencies.rand_xorshift]
version = "0.2"

[dependencies.thiserror]
version = "1.0"

[dev-dependencies.snarkos-storage]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"