[package]
name = "leo-compiler"
version = "1.0.6"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "Compiler of the Leo programming language"
homepage = "https://aleo.org"
repository = "https://github.com/AleoHQ/leo"
keywords = [
  "aleo",
  "cryptography",
  "leo",
  "programming-language",
  "zero-knowledge"
]
categories = [ "cryptography::cryptocurrencies", "web-programming" ]
include = [ "Cargo.toml", "src", "README.md", "LICENSE.md" ]
license = "GPL-3.0"
edition = "2018"

[dependencies.leo-ast]
path = "../ast"
version = "1.0.6"

[dependencies.leo-core]
path = "../core"
version = "1.0.6"

[dependencies.leo-gadgets]
path = "../gadgets"
version = "1.0.6"

[dependencies.leo-grammar]
path = "../grammar"
version = "1.0.6"

[dependencies.leo-imports]
path = "../imports"
version = "1.0.6"

[dependencies.leo-input]
path = "../input"
version = "1.0.6"

[dependencies.leo-package]
path = "../package"
version = "1.0.6"

[dependencies.leo-state]
path = "../state"
version = "1.0.6"

[dependencies.leo-symbol-table]
path = "../symbol-table"
version = "1.0.6"

[dependencies.leo-type-inference]
path = "../type-inference"
version = "1.0.6"

[dependencies.snarkos-curves]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"

[dependencies.snarkos-dpc]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"

[dependencies.snarkos-errors]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"

[dependencies.snarkos-gadgets]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"

[dependencies.snarkos-models]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"

[dependencies.snarkos-objects]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"

[dependencies.snarkos-utilities]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"

[dependencies.bincode]
version = "1.0"

[dependencies.hex]
version = "0.4.2"

[dependencies.indexmap]
version = "1.6.0"
features = ["serde-1"]

[dependencies.pest]
version = "2.0"

[dependencies.rand]
version = "0.7"

[dependencies.rand_xorshift]
version = "0.2"
default-features = false

[dependencies.serde]
version = "1.0"

[dependencies.sha2]
version = "0.9"

[dependencies.thiserror]
version = "1.0"

[dependencies.tracing]
version = "0.1"

[dependencies.tracing-subscriber]
version = "0.2"

[dev-dependencies.num-bigint]
version = "0.3"

[dev-dependencies.snarkos-algorithms]
git = "https://github.com/AleoHQ/snarkOS"
branch = "test/blake2-one-round"

[features]
default = [ ]
ci_skip = [ "leo-grammar/ci_skip", "leo-ast/ci_skip" ]
